### ISSUE TITLE
agent 日志会时常报错，不定时，不定项目

### ISSUE THREAD

**Issue by caltonwu** [XWJR-Ops/zabbix-RDS-monitor#1]
failed to kill [/opt/python/bin/python2.7 /bin/zabbix/check_rds.py Performance rm-xxxxxxxxxxxxxxxxxxn com_delete]: [1] Operation not permitted

手动执行能正常获取到值

**Comment by X-Mars** [comment]
要从zabbix入手排查
开发环境：
zabbix-server：3.0
zabbix-agent：3.0
建议你测试看看

**Comment by sky1006** [comment]
脚本放在zabbix server上，怎么添加主机和模板关联的，我取不到数据，能说一下你的操作步骤吗？
