### ISSUE TITLE
非常感谢作者的共享，现在已经实现通过监控项别名对RDS的监控

### ISSUE THREAD

**Issue by zyzfzb** [XWJR-Ops/zabbix-RDS-monitor#10]
期待以rds实例分组的版本

**Comment by XDongo** [comment]
有出现过timeout的情况吗？ 数据断断续续的

**Comment by AlliotTech** [comment]
> 有出现过timeout的情况吗？ 数据断断续续的

应该是阿里SDK限制单用户500次调用的问题？

**Comment by charnet1019** [comment]
遇到过，通过将被动模式改为主动模式后就可以了发自我的华为手机-------- 原始邮件 --------发件人： Alliot <notifications@github.com>日期： 2021年1月15日周五 14:47收件人： XWJR-Ops/zabbix-RDS-monitor <zabbix-RDS-monitor@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [XWJR-Ops/zabbix-RDS-monitor] 非常感谢作者的共享，现在已经实现通过监控项别名对RDS的监控 (#10)



有出现过timeout的情况吗？ 数据断断续续的



应该是阿里SDK限制单用户500次调用的问题？
