### ISSUE TITLE
zabbix 3.4.8  导入模板无法显示

### ISSUE THREAD

**Issue by avyou** [XWJR-Ops/zabbix-RDS-monitor#6]
zabbix 3.4.8  导入模板无法显示，也主是找不到模板，可以放一个3.4的出来吗

**Comment by X-Mars** [comment]
没有 3.4.8的环境
你可以搭建个3.0版本
看着模板内容 在 3.4 创建模板

**Comment by chaiqinghu** [comment]
3.4.13 . 是可以的但是我不知道是否将rds 添加监控了

**Comment by yyinfor** [comment]
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 404 Error:InvalidAccessKeyId.NotFound Specified access key is not found. RequestID: E0D2C649-B2EA-4DF5-ACE7-467FN4235FB2
我已经修改了check_rds.py 里面的ID和Secret 而且是权限最高的，我的RDS是在香港，请问是跟这个有关吗？RegionId = 'cn-hongkong'   我是这样设置的，然后报上面的错，麻烦看到留言请回复一下，谢谢了！！！

**Comment by X-Mars** [comment]
检查你的key吧，不行就提工单

**Comment by yyinfor** [comment]
好的，谢谢了！


----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："X-Mars "<notifications@github.com>;
发送时间：2018年9月18日(星期二) 晚上8:34
收件人："XWJR-Ops/zabbix-RDS-monitor" <zabbix-RDS-monitor@noreply.github.com>;
抄送："yyinfor "<zhanglin@yyinfor.cn>;"Comment "<comment@noreply.github.com>;
主题：Re: [XWJR-Ops/zabbix-RDS-monitor] zabbix 3.4.8  导入模板无法显示 (#6)
-----------------------------------

 
检查你的key吧，不行就提工单

**Comment by zyzfzb** [comment]
alue "Traceback (most recent call last):
File "/etc/zabbix/script/check_rds.py", line 116, in <module>
GetPerformance(DBInstanceId, MasterKey, IndexNum, StartTime, EndTime)
File "/etc/zabbix/script/check_rds.py", line 40, in GetPerformance
PerformanceInfo = clt.do_action_with_exception(Performance)
File "/usr/lib/python2.7/site-packages/aliyunsdkcore/client.py", line 262, in do_action_with_exception
request_id=request_id)
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 404 Error:InvalidAccessKeyId.NotFound Specified access key is not found. RequestID: B395284E-9787-4083-9BCF-762FCD230402" of type "string" is not suitable for value type "Numeric (float)"
