### ISSUE TITLE
zabbix  界面显示不出来

### ISSUE THREAD

**Issue by ghost** [XWJR-Ops/zabbix-RDS-monitor#7]
环境 : python2.7  | pip 2.7 | zabbix 3.2.10
 
这个对环境有都有什么要求？

**Comment by X-Mars** [comment]
基于  zabbix3.0 做的  ，
你可以通过[脚本](https://github.com/X-Mars/Quick-Installation-ZABBIX)安装个3.0
，导入摸板后升级3.2，再将模板导出。
