### ISSUE TITLE
NotFound Specified access key is not found. 

### ISSUE THREAD

**Issue by zyzfzb** [XWJR-Ops/zabbix-RDS-monitor#9]
执行discovery_rds.py脚本正常获取RDS信息，但是导入模板后，所有的item都提示如下信息：
alue "Traceback (most recent call last):
File "/etc/zabbix/script/check_rds.py", line 116, in <module>
GetPerformance(DBInstanceId, MasterKey, IndexNum, StartTime, EndTime)
File "/etc/zabbix/script/check_rds.py", line 40, in GetPerformance
PerformanceInfo = clt.do_action_with_exception(Performance)
File "/usr/lib/python2.7/site-packages/aliyunsdkcore/client.py", line 262, in do_action_with_exception
request_id=request_id)
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 404 Error:InvalidAccessKeyId.NotFound Specified access key is not found. RequestID: B395284E-9787-4083-9BCF-762FCD230402" of type "string" is not suitable for value type "Numeric (float)"

**Comment by X-Mars** [comment]
字面意思，可以联系阿里云售后。
